#!/usr/bin/env pwsh
# Script de creation des issues GitHub pour le cahier des charges restaurant
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8

$repo = "EmileDeslau/Projects"

# Milestone mapping: 1=Phase1 MVP, 2=Phase2 Cuisine, 3=Phase3 En ligne, 4=Phase4 Avance
$issues = @(
    @{t="[M-07] Creer une commande"; b="**ID:** M-07 | **Priorite:** MUST HAVE | **Module:** Commandes`n`nAssocier une commande a une table ou a un client (emporter/livraison).`n`n- [ ] Creation de commande liee a une table`n- [ ] Creation de commande a emporter`n- [ ] Horodatage automatique"; labels=@("must-have","commandes"); ms=1}
    @{t="[M-08] Ajouter des articles avec quantite et recalcul prix"; b="**ID:** M-08 | **Priorite:** MUST HAVE | **Module:** Commandes / Tarification`n`nSelection d'articles, modification de quantite, recalcul automatique du prix selon les paliers.`n`n- [ ] Ajout d'articles depuis le menu`n- [ ] Modification de quantite avec recalcul dynamique`n- [ ] Affichage du palier de prix applique`n- [ ] Total mis a jour en temps reel"; labels=@("must-have","commandes"); ms=1}
    @{t="[M-09] Modifier une commande en cours"; b="**ID:** M-09 | **Priorite:** MUST HAVE | **Module:** Commandes`n`nAjouter/retirer des articles, changer les quantites.`n`n- [ ] Ajout/suppression d'articles`n- [ ] Modification des quantites`n- [ ] Recalcul automatique des prix"; labels=@("must-have","commandes"); ms=1}
    @{t="[M-10] Annuler une commande"; b="**ID:** M-10 | **Priorite:** MUST HAVE | **Module:** Commandes`n`nAnnulation totale ou partielle avec motif.`n`n- [ ] Annulation totale ou partielle`n- [ ] Motif d'annulation obligatoire`n- [ ] Tracabilite dans le journal"; labels=@("must-have","commandes"); ms=1}
    @{t="[M-11] Statuts de commande (workflow)"; b="**ID:** M-11 | **Priorite:** MUST HAVE | **Module:** Commandes`n`nEn attente > En preparation > Prete > Servie > Cloturee`n`n- [ ] 5 statuts distincts`n- [ ] Transitions validees`n- [ ] Notification a chaque changement"; labels=@("must-have","commandes"); ms=1}
    @{t="[M-12] Notes et instructions speciales (allergies)"; b="**ID:** M-12 | **Priorite:** MUST HAVE | **Module:** Commandes`n`nAllergies, preferences, cuisson, sans gluten...`n`n- [ ] Champ texte libre par article`n- [ ] Affichage visible en cuisine`n- [ ] Tags pour allergies courantes"; labels=@("must-have","commandes"); ms=1}
    @{t="[M-13] Plan de salle configurable"; b="**ID:** M-13 | **Priorite:** MUST HAVE | **Module:** Tables`n`nCreer/positionner les tables, definir capacite.`n`n- [ ] Ajout/suppression de tables`n- [ ] Position et capacite configurables`n- [ ] Vue graphique du plan de salle"; labels=@("must-have","tables"); ms=1}
    @{t="[M-14] Statut des tables"; b="**ID:** M-14 | **Priorite:** MUST HAVE | **Module:** Tables`n`nLibre > Occupee > Reservee > A nettoyer`n`n- [ ] 4 statuts visuels distincts`n- [ ] Mise a jour en temps reel`n- [ ] Code couleur"; labels=@("must-have","tables"); ms=1}
    @{t="[M-15] Associer une commande a une table"; b="**ID:** M-15 | **Priorite:** MUST HAVE | **Module:** Tables / Commandes`n`nLien direct table-commande active.`n`n- [ ] Association automatique a l'ouverture de commande`n- [ ] Visualisation de la commande depuis le plan de salle"; labels=@("must-have","tables"); ms=1}
    @{t="[M-16] Generer l'addition avec details paliers"; b="**ID:** M-16 | **Priorite:** MUST HAVE | **Module:** Facturation`n`nRecapitulatif detaille avec prix unitaires par palier et totaux.`n`n- [ ] Detail par article avec palier applique`n- [ ] Sous-total, TVA, total TTC`n- [ ] Indication des economies realisees"; labels=@("must-have","facturation"); ms=1}
    @{t="[M-17] Modes de paiement (CB, especes, ticket resto)"; b="**ID:** M-17 | **Priorite:** MUST HAVE | **Module:** Facturation`n`nCB, Especes, Ticket restaurant, Paiement mixte.`n`n- [ ] Selection du mode de paiement`n- [ ] Paiement mixte (combiner plusieurs modes)`n- [ ] Validation et cloture"; labels=@("must-have","facturation"); ms=1}
    @{t="[M-18] Division de l'addition"; b="**ID:** M-18 | **Priorite:** MUST HAVE | **Module:** Facturation`n`nPartager par nombre de convives ou par article.`n`n- [ ] Split egal par nombre de personnes`n- [ ] Split par article`n- [ ] Paiement individuel"; labels=@("must-have","facturation"); ms=1}
    @{t="[M-19] Impression / envoi du ticket"; b="**ID:** M-19 | **Priorite:** MUST HAVE | **Module:** Facturation`n`nImpression thermique ou envoi par e-mail/SMS.`n`n- [ ] Impression sur imprimante thermique`n- [ ] Envoi par e-mail`n- [ ] Format PDF"; labels=@("must-have","facturation"); ms=1}
    @{t="[M-20] TVA configurable par categorie"; b="**ID:** M-20 | **Priorite:** MUST HAVE | **Module:** Facturation`n`nTaux par categorie (sur place / a emporter).`n`n- [ ] Configuration des taux de TVA`n- [ ] Taux differents sur place vs emporter`n- [ ] Calcul automatique"; labels=@("must-have","facturation"); ms=1}
    @{t="[M-21] Ecran de commandes en cuisine (KDS)"; b="**ID:** M-21 | **Priorite:** MUST HAVE | **Module:** Cuisine`n`nListe des commandes en attente, triees par anciennete.`n`n- [ ] Affichage temps reel des commandes`n- [ ] Tri par anciennete`n- [ ] Code couleur selon le temps d'attente"; labels=@("must-have","cuisine"); ms=2}
    @{t="[M-22] Marquage Pret par le cuisinier"; b="**ID:** M-22 | **Priorite:** MUST HAVE | **Module:** Cuisine`n`nLe cuisinier valide la preparation, notification au serveur.`n`n- [ ] Bouton de validation par commande/article`n- [ ] Notification push au serveur`n- [ ] Archivage automatique"; labels=@("must-have","cuisine"); ms=2}
    @{t="[M-23] Connexion securisee (login + PIN)"; b="**ID:** M-23 | **Priorite:** MUST HAVE | **Module:** Auth`n`nLogin/mot de passe ou code PIN rapide (serveurs).`n`n- [ ] Authentification classique (email/password)`n- [ ] Code PIN rapide pour les serveurs`n- [ ] Verrouillage apres X tentatives"; labels=@("must-have","auth"); ms=2}
    @{t="[M-24] Gestion des roles et permissions"; b="**ID:** M-24 | **Priorite:** MUST HAVE | **Module:** Auth`n`nAdmin, Serveur, Cuisinier, Caissier - permissions distinctes.`n`n- [ ] 4 roles predefinis`n- [ ] Matrice de permissions par role`n- [ ] Attribution de role par utilisateur"; labels=@("must-have","auth"); ms=2}
    @{t="[M-25] Journal d'activite (audit log)"; b="**ID:** M-25 | **Priorite:** MUST HAVE | **Module:** Auth`n`nTracabilite : qui a fait quoi, quand.`n`n- [ ] Log de toutes les actions critiques`n- [ ] Filtrage par utilisateur/date/type`n- [ ] Non modifiable/non supprimable"; labels=@("must-have","auth"); ms=2}
    @{t="[S-01] Menu consultable en ligne (QR code)"; b="**ID:** S-01 | **Priorite:** SHOULD HAVE | **Module:** En ligne`n`nPage web / QR code avec les prix dynamiques affiches.`n`n- [ ] Page publique responsive`n- [ ] Prix dynamiques visibles`n- [ ] QR code generable par table"; labels=@("should-have","en-ligne"); ms=3}
    @{t="[S-02] Commande a emporter / livraison en ligne"; b="**ID:** S-02 | **Priorite:** SHOULD HAVE | **Module:** En ligne`n`nLe client compose sa commande, voit les prix varier en temps reel.`n`n- [ ] Panier interactif`n- [ ] Recalcul dynamique des prix`n- [ ] Choix emporter/livraison"; labels=@("should-have","en-ligne"); ms=3}
    @{t="[S-03] Paiement en ligne (Stripe/PayPal)"; b="**ID:** S-03 | **Priorite:** SHOULD HAVE | **Module:** En ligne`n`nIntegration Stripe / PayPal.`n`n- [ ] Paiement securise (PCI DSS)`n- [ ] Confirmation automatique`n- [ ] Remboursement possible"; labels=@("should-have","en-ligne"); ms=3}
    @{t="[S-04] Suivi de commande en temps reel (client)"; b="**ID:** S-04 | **Priorite:** SHOULD HAVE | **Module:** En ligne`n`nStatut en temps reel : preparation, pret, en livraison.`n`n- [ ] Page de suivi avec lien unique`n- [ ] Mise a jour WebSocket`n- [ ] Notification quand pret"; labels=@("should-have","en-ligne"); ms=3}
    @{t="[S-05] Suivi des ingredients en stock"; b="**ID:** S-05 | **Priorite:** SHOULD HAVE | **Module:** Stocks`n`nQuantite en stock, seuil d'alerte.`n`n- [ ] CRUD ingredients`n- [ ] Quantite actuelle et seuil minimum`n- [ ] Association ingredients-articles"; labels=@("should-have","stocks"); ms=4}
    @{t="[S-06] Deduction automatique du stock"; b="**ID:** S-06 | **Priorite:** SHOULD HAVE | **Module:** Stocks`n`nReduction du stock a chaque commande validee.`n`n- [ ] Calcul automatique selon la recette`n- [ ] Mise a jour en temps reel`n- [ ] Rollback si annulation"; labels=@("should-have","stocks"); ms=4}
    @{t="[S-07] Alertes de rupture de stock"; b="**ID:** S-07 | **Priorite:** SHOULD HAVE | **Module:** Stocks`n`nNotification quand un ingredient passe sous le seuil.`n`n- [ ] Alerte visuelle dans le dashboard`n- [ ] Notification push a l'admin`n- [ ] Desactivation auto de l'article si rupture totale"; labels=@("should-have","stocks"); ms=4}
    @{t="[S-08] Systeme de reservation"; b="**ID:** S-08 | **Priorite:** SHOULD HAVE | **Module:** Reservations`n`nDate, heure, nombre de couverts, nom du client.`n`n- [ ] Formulaire de reservation`n- [ ] Calendrier des reservations`n- [ ] Gestion des conflits"; labels=@("should-have","reservations"); ms=4}
    @{t="[S-09] Confirmation automatique (email/SMS)"; b="**ID:** S-09 | **Priorite:** SHOULD HAVE | **Module:** Reservations`n`nE-mail/SMS de confirmation et rappel.`n`n- [ ] Envoi automatique a la creation`n- [ ] Rappel J-1`n- [ ] Lien d'annulation"; labels=@("should-have","reservations"); ms=4}
    @{t="[S-10] Integration reservations au plan de salle"; b="**ID:** S-10 | **Priorite:** SHOULD HAVE | **Module:** Reservations / Tables`n`nAttribution automatique des tables.`n`n- [ ] Suggestion de table selon capacite`n- [ ] Blocage de la table a l'heure reservee`n- [ ] Vue planning par table"; labels=@("should-have","reservations"); ms=4}
    @{t="[S-11] Compte client avec historique"; b="**ID:** S-11 | **Priorite:** SHOULD HAVE | **Module:** Fidelite`n`nHistorique de commandes, preferences.`n`n- [ ] Creation de compte client`n- [ ] Historique des commandes`n- [ ] Preferences enregistrees"; labels=@("should-have","fidelite"); ms=4}
    @{t="[S-12] Points de fidelite"; b="**ID:** S-12 | **Priorite:** SHOULD HAVE | **Module:** Fidelite`n`nCumul de points selon le montant depense.`n`n- [ ] Attribution automatique de points`n- [ ] Solde de points visible`n- [ ] Regles configurables"; labels=@("should-have","fidelite"); ms=4}
    @{t="[S-13] Reductions fidelite par paliers"; b="**ID:** S-13 | **Priorite:** SHOULD HAVE | **Module:** Fidelite`n`nPaliers de recompenses (ex: -10pct apres 500 points).`n`n- [ ] Paliers de recompenses configurables`n- [ ] Application automatique de la reduction`n- [ ] Notification au client"; labels=@("should-have","fidelite"); ms=4}
    @{t="[S-14] Dashboard temps reel"; b="**ID:** S-14 | **Priorite:** SHOULD HAVE | **Module:** Rapports`n`nCA du jour, commandes en cours, taux d'occupation.`n`n- [ ] Widgets configurables`n- [ ] Mise a jour en temps reel`n- [ ] KPIs principaux"; labels=@("should-have","rapports"); ms=4}
    @{t="[S-15] Rapports de vente"; b="**ID:** S-15 | **Priorite:** SHOULD HAVE | **Module:** Rapports`n`nPar periode, par article, par categorie.`n`n- [ ] Filtres par date`n- [ ] Classement des articles`n- [ ] Graphiques"; labels=@("should-have","rapports"); ms=4}
    @{t="[S-16] Analyse de l'impact des paliers de prix"; b="**ID:** S-16 | **Priorite:** SHOULD HAVE | **Module:** Rapports / Tarification`n`nStatistiques sur les quantites commandees et l'impact des paliers.`n`n- [ ] Repartition par palier`n- [ ] Revenus par palier`n- [ ] Recommandations de paliers optimaux"; labels=@("should-have","rapports"); ms=4}
    @{t="[S-17] Export des donnees (CSV/PDF)"; b="**ID:** S-17 | **Priorite:** SHOULD HAVE | **Module:** Rapports`n`nExport pour la comptabilite.`n`n- [ ] Export CSV`n- [ ] Export PDF`n- [ ] Planification d'exports automatiques"; labels=@("should-have","rapports"); ms=4}
    @{t="[S-18] Interface multilingue (FR/EN)"; b="**ID:** S-18 | **Priorite:** SHOULD HAVE | **Module:** UX`n`nFR / EN minimum.`n`n- [ ] Systeme i18n`n- [ ] Traduction complete FR/EN`n- [ ] Selection de langue par utilisateur"; labels=@("should-have"); ms=4}
    @{t="[S-19] Accessibilite WCAG 2.1 AA"; b="**ID:** S-19 | **Priorite:** SHOULD HAVE | **Module:** UX`n`nConformite WCAG 2.1 AA.`n`n- [ ] Contraste des couleurs`n- [ ] Navigation au clavier`n- [ ] Lecteur d'ecran compatible"; labels=@("should-have"); ms=4}
)

$count = 0
foreach ($issue in $issues) {
    $payload = @{
        title = $issue.t
        body = $issue.b
        labels = $issue.labels
        milestone = $issue.ms
    } | ConvertTo-Json -Compress
    $payload | gh api "repos/$repo/issues" --input - 2>&1 | Out-Null
    $count++
    Write-Host "[$count/$($issues.Count)] $($issue.t)"
}

Write-Host "`nTermine: $count issues creees."
